{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "openwebui" }}
  labels:
    {{- include "owui-stack.labels" . | nindent 4 }}
{{- end }}