apiVersion: v1
kind: Secret
metadata:
  name: {{ include "owui-stack.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default "openwebui" }}
  labels:
    {{- include "owui-stack.labels" . | nindent 4 }}
type: Opaque
data:
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  LITELLM_API_KEY: {{ .Values.secrets.litellmApiKey | b64enc | quote }}
  
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.secrets.awsRegion | b64enc | quote }}
  
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | b64enc | quote }}
  GITLAB_TOKEN: {{ .Values.secrets.gitlabToken | b64enc | quote }}
  GITLAB_URL: {{ .Values.secrets.gitlabUrl | b64enc | quote }}
  
  AZURE_TENANT_ID: {{ .Values.secrets.azureTenantId | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Values.secrets.azureClientId | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.secrets.azureClientSecret | b64enc | quote }}
  
  FUNCTION_PREFIX: {{ .Values.secrets.functionPrefix | b64enc | quote }}
  FUNCTION_LIST: {{ .Values.secrets.functionList | b64enc | quote }}
  FUNCTION_TAG_KEY: {{ .Values.secrets.functionTagKey | b64enc | quote }}
  FUNCTION_TAG_VALUE: {{ .Values.secrets.functionTagValue | b64enc | quote }}
  
  GRAFANA_API_KEY: {{ .Values.secrets.grafanaApiKey | b64enc | quote }}
  GRAFANA_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | b64enc | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | b64enc | quote }}
  
  PROMETHEUS_USERNAME: {{ .Values.secrets.prometheusUsername | b64enc | quote }}
  PROMETHEUS_PASSWORD: {{ .Values.secrets.prometheusPassword | b64enc | quote }}
  
  MEMCACHED_HOST: {{ .Values.secrets.memcachedHost | b64enc | quote }}
  MEMCACHED_PORT: {{ .Values.secrets.memcachedPort | b64enc | quote }}
  
  OPENWEBUI_ADMIN_USERNAME: {{ .Values.secrets.openwebuiAdminUsername | b64enc | quote }}
  OPENWEBUI_ADMIN_PASSWORD: {{ .Values.secrets.openwebuiAdminPassword | b64enc | quote }}
  OPENWEBUI_ADMIN_EMAIL: {{ .Values.secrets.openwebuiAdminEmail | b64enc | quote }}
