# Custom values for OpenWebUI Stack

# Global settings
global:
  # Specify your storage class if needed
  # storageClass: "standard"
  namespace: openwebui

# API Keys (fill these in with your actual keys)
secrets:
  anthropicApiKey: ""
  openaiApiKey: ""
  gitlabToken: ""
  githubToken: ""
  
  # Admin credentials (you should change these)
  openwebuiAdminUsername: "admin"
  openwebuiAdminPassword: "admin"
  openwebuiAdminEmail: "admin@example.com"
  
  grafanaAdminUser: "admin"
  grafanaAdminPassword: "admin"

# Ollama settings
ollama:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 8Gi
  persistence:
    size: 40Gi
  # Set to true if you have GPU support
  gpu:
    enabled: false

# OpenWebUI settings
openwebui:
  service:
    # Uncomment to expose OpenWebUI through a LoadBalancer
    # loadBalancer:
    #   enabled: true
    #   port: 80
    
    # Uncomment to expose OpenWebUI through an Ingress
    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #   hosts:
    #     - host: openwebui.example.com
    #       paths:
    #         - path: /
    #           pathType: Prefix
  
  # Disable authentication (not recommended for production)
  auth:
    disabled: false
    
  # Set default MCP tools
  mcp:
    defaultTools: "memory,filesystem,prometheus,grafana"
    enableGlobalFunctions: true

# MCPO settings
mcpo:
  # Set to false in production
  mockMode: true

# Persistence sizes
prometheus:
  persistence:
    size: 20Gi

grafana:
  persistence:
    size: 5Gi

loki:
  persistence:
    size: 20Gi

mimir:
  persistence:
    size: 20Gi

# Disable components you don't need
# nodeExporter:
#   enabled: false

# cadvisor:
#   enabled: false

# alertmanager:
#   enabled: false

# Resource limits for monitoring stack
# Adjust these based on your cluster resources
prometheus:
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi

grafana:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

loki:
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi
